version: '3.9'
services:
  runner:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - REPO=Nuwa-genomics/Nuwa
      - TOKEN=<CHANGE>
    # deploy:
    #   mode: replicated
    #   replicas: 4
